sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jyu0NvVzy3aK0Z7xOy/3PgA38GdzHqJv8nMqcNRdMsXSa6edWfrnO6+oT5jOHejFN6SpdFRw6OpN+cV9LAhyCfyuWROwpHaOj5onGCx+jFtTmw+UJbiCoJsk62HKI2WBfm3vLecdvDWZ+tTDe1sdeL3QTK+6n8VcS4HQVaOhRLIuQIl9E6fN8PU3cUuTmGvg4tmuKrehRcTJ9Ge1JhgkhaoPMFeY2xgGRlydh86coKS2sTCXYW+n8bRuc/fEhfj/5JJaQPWsohGCq0A9PoOUsXMkaQpvyvIFf2MY+h8fp6blU3jY2CsND5dIdcyFJ3oQKvTKUulaP75YqYApGko39kYppm9wVhfZ9DTDaornoVpPD/31og74i9XU3ESQv8LMCp5Yn/acHlMRbVKtURrcmIsimZzlDKGLb+iNwYxSxtZzeP3fU0PYLJzIaAg8Cm7Sa9YlnP79K2Y/RxDvLcef7VOzQCf2oQ3Kt98QAJl0fDCKjSuMcZolAj9nPK0Ssgt/yooyFircafLud3dRl04XQZSR3s6n0EyBnxsCPt7VbW8KGscnSZZfCa5XTgJJx+yrHOzh1dz/TKaL0vIfF33Xfw17oHidr8czhgHGN/OZWUMasPy8n5LtTItTutgtyhqM3BxPXX/xxSjaBf23IRrPfBLaczIm+WGVZ3bO9RcWUL4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Historical-Lectures-and-Essays_1360
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy